micronaut:
  application:
    name: oda-widget-service
  security:
    token:
      bearer:
        enabled: true
      cookie:
        enabled: true
      jwt:
        signatures:
          jwks:
            keycloak:
              url: https://auth.oda.digital/realms/ODA/protocol/openid-connect/certs
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
flyway:
  datasources:
    default:
      enabled: true
jpa:
  default:
    entity-scan:
        packages: 'io.github.stcarolas.oda.widget'
infinispan.url: ${INFINISPAN_HOST:`127.0.0.1`}
