datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost/postgres?currentSchema=widget`}
    username: ${JDBC_USER:`postgres`}
    password: ${JDBC_PASSWORD:`postgres`}
    driverClassName: 'org.postgresql.Driver'
rabbitmq.host: ${RABBITMQ_HOST:`localhost`}
