name: Release

on:
  push:
    branches: ["master"]

permissions: write-all

jobs:
  build-and-deploy:
    uses: "OpenDonationAssistant/oda-libraries/.github/workflows/build_and_deploy_native_with_client_package.yml@master"
    secrets: inherit
    with:
      service: widgets-service
      version: "${{ github.RUN_NUMBER }}"
